#the user must first have a Twilio account
#and have Twilio installed on the computer
from twilio.rest import TwilioRestClient

Account_SID="" #your account SID
Auth_token="" #the authentication token generated by Twilio

client=TwilioRestClient(Account_SID,Auth_token)

client.messages.create(
    to="" #enter the destination phone numeber
    from_="" #enter your phone number
    body="Hey all!" #body of your message
)
